[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/ncaRnoVEsPGcmyL15TihN"}
via_ir = true 

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@ccip/=lib/ccip/',
    '@chainlink-local=lib/chainlink-local/',
    'forge-std/=lib/forge-std/src/'
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
